######################################################################
# Automatically generated by qmake (2.01a) Fri Mar 2 14:16:04 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += VolumeDataDialog.hpp
SOURCES += main.cpp VolumeDataDialog.cpp
